export const GET_CARET_POSITION = "GET_CARET_POSITION";

export const ADD_LINE_POSITION = "ADD_LINE_POSITION";
export const ADD_COLUMN_POSITION = "ADD_COLUMN_POSITION";
export const SET_COLUMN_POSITION = "SET_COLUMN_POSITION";

export const REMOVE_LINE_POSITION = "REMOVE_LINE_POSITION";
export const REMOVE_COLUMN_POSITION = "REMOVE_COLUMN_POSITION";