export const GET_CODE_TEXT = "GET_CODE_TEXT";

export const GET_MARKDOWN_CODE = "GET_MARKDOWN_CODE";

export const UPDATE_CODE_TEXT = "UPDATE_CODE_TEXT";
export const REMOVE_CODE_TEXT = "REMOVE_CODE_TEXT";

export const TRANSMIT_CODE_TO_BACKEND = "TRANSMIT_CODE_TO_BACKEND";