export const COPY_TEXT_INPUT_BLOCK = "COPY_TEXT_INPUT_BLOCK";
export const CUT_TEXT_INPUT_BLOCK = "CUT_TEXT_INPUT_BLOCK";
export const PASTE_TEXT_INPUT_BLOCK = "PASTE_TEXT_INPUT_BLOCK";
export const ADD_TEXT_INPUT_BLOCK = "ADD_TEXT_INPUT_BLOCK";
export const FLUSH_TEXT_INPUT_BLOCK = "FLUSH_TEXT_INPUT_BLOCK";
