export const HOVER_WARNINGS = "HOVER_WARNINGS_STATUS_BAR";
export const HOVER_ERRORS = "HOVER_ERRORS_STATUS_BAR";
export const CLOSE_WARNINGS = "CLOSE_WARNINGS_STATUS_BAR";
export const CLOSE_ERRORS = "CLOSE_ERRORS_STATUS_BAR";

export const ADD_WARNING = "ADD_WARNING_STATUS_BAR";
export const REMOVE_WARNING = "REMOVE_WARNING_STATUS_BAR";
export const ADD_ERROR = "ADD_ERROR_STATUS_BAR";
export const REMOVE_ERROR = "REMOVE_ERROR_STATUS_BAR";