export const STATUS_HOVER = "STATUS_BAR_HOVER";
export const STATUS_CLOSE = "STATUS_BAR_CLOSE";

export const ADD_ELEMENT_TO_BLOCK = "ADD_ELEMENT_TO_BLOCK";

export const EXCEPTION = "EXCEPTION";

export const ADD_WARNINGS_AND_ERRORS_AMOUNTS = "ADD_WARNINGS_AND_ERRORS_AMOUNTS";