export const NEW_FILE_CREATE = "NEW_FILE_CREATE_WINDOW";
export const OPEN_FILE = "OPEN_FILE_WINDOW";

export const SAVE_FILE_WINDOW = "SAVE_FILE_WINDOW";
export const SAVE_AS_FILE_WINDOW = "SAVE_AS_FILE_WINDOW";

export const ABOUT_PROGRAMM = "ABOUT_PROGRAM_WINDOW";
export const HELPER_PROGRAMM = "HELPER_PROGRAM_WINDOW";

export const EXIT_FROM_WINDOW = "EXIT_FROM_WINDOW";