export const ABOUT_PROGRAMM = "ABOUT_PROGRAM_WINDOW";
export const HELPER_PROGRAMM = "HELPER_PROGRAM_WINDOW";

export const EXIT_FROM_WINDOW = "EXIT_FROM_WINDOW";

export const MAIN_PAGE_LOCATION = "MAINPAGE_LOCATION";
export const PROJECT_PAGE_LOCATION = "PROJECT_PAGE_LOCATION";
export const SIGNUP_PAGE_LOCATION = "SIGNUP_PAGE_LOCATION";
export const SIGNIN_PAGE_LOCATION = "SIGNIN_PAGE_LOCATION";

export const CREATE_NEW_CODE_FILE_WINDOW = "CREATE_NEW_CODE_FILE_MODAL";
export const OPEN_FILE_FROM_LOCAL_DISK = "OPEN_FILE_FROM_LOCAL_DISK_MODAL";
export const SAVE_AS_FILE_TO_LOCAL_DISK = "SAVE_FILE_TO_LOCAL_DISK_MODAL";